---
- name: start new aws infrastructure
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/base_{{Stage}}.yml
  tasks:
  - name: create vpc
    include_tasks: tasks/vpc.yml

  - name: create ecr 
    ecs_ecr: 
        name: services
        region: "{{region}}"   
    register: ecr
 
  - name: create redis
    include_tasks: tasks/redis.yml

  - name: create rds
    include_tasks: tasks/rds.yml

  - name: create ec2
    include_tasks: tasks/ec2.yml

 - name: debug events
    debug: msg="{{ecr.repository.repositoryUri}} {{redis.stack_outputs.RedisAddress}}:6379"
  
- name: playbook on docker swarm master
  hosts: docker[0:2]
  gather_facts: false
  tasks:
  - name: create docker swarm master
    include_tasks: tasks/docker_swarm_master.yml
 
  #- name: Clone git repository
  #  git: 
  #    repo: https://github.com/allen12921/myapp.git
  #    dest: $HOME/myapp
  #    version: "{{release_tag}}"
  #    force: yes
  #  register: appsrc
  #  run_once: true
  
  #- name: Build app image and push it to ecr
  #  docker_image:
  #    path: dockerfile
  #    name: "{{ecr}}/myapp"
  #    tag: "{{appsrc.after}}"
  #    push: no
  #  when: appsrc.changed
  #  run_once: true
  handlers:
  - name: restart docker
    service: name=docker state=restarted enabled=yes  
  #- name: create or update myapp ecs service
  #  register: myapp 
#delegate_to:
#handlers:
