---
- name: copy docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
- name: install docker-ce
  yum: name=docker-ce-18.09.5-3.el7 state=present
  notify: restart docker
- meta: flush_handlers
- name: init docker swarm cluster
  docker_swarm:
     state: present
  run_once: true
#  shell: docker swarm init
  ignore_errors: yes
- name: find out master join key
  shell: docker swarm join-token manager 
  register: manager_token
- name: find out worker join key
  shell: docker swarm join-token worker
  register: worker_token
- name: add dummy host to save variables
  add_host:
   name: "SWARM_TOKEN_HOLDER"
   manager_token:   "{{manager_token.stdout_lines[2]}}"
   worker_token: "{{worker_token.stdout_lines[2]}}"
#- name: join swarm as manager
#  shell: "{{ hostvars['SWARM_TOKEN_HOLDER']['manager_token'] }}" 
#  when: swarm_role == "manager"
#- name: join swarm as worker
#  shell: "{{ hostvars['SWARM_TOKEN_HOLDER']['worker_token'] }}"
#  when: swarm_role == "worker"

#when: when: inventory_hostname is not groups['docker'][0]
